# configuration file for production environment

# only log warning and error messsages
log: "warning"

# log message to a file in logs/
#logger: "file"

# don't consider warnings critical
warnings: 0

# hide errors
show_errors: 0

# cache route resolution for maximum performance
route_cache: 1

engines:
  # Workaround horrible Return::MultiLevel issues. Nasty bug causing a
  # longjump out of Template::Document::process(), when a template causes a
  # Log::Report fatal error. The fatal error causes a redirect within
  # Plugin::LogReport, which means that the code jumps out of the eval() in
  # Template::Document. As a result, _HOT is not set to zero and the next
  # time the template is called TT thinks there is a recursive loop. The only
  # other solutions are something more intrusive such as improving the TT
  # Dancer2 plugin or creating a new one.
  template:
    template_toolkit:
      RECURSION: 1
  logger:
    LogReport:
      app_name: GADS
